[package]
name = "lnk"
version = "0.2.0"
authors = ["Lily Hopkins <bsalarius@gmail.com>"]
edition = "2018"
description = "A Rust library to parse and write Windows shortcut files (.lnk)"
license = "MIT"
repository = "https://github.com/lilopkins/lnk-rs"

[dependencies]
bitflags = "1.2.1"
byteorder = "1.3.4"
num-traits = "0.2.11"
num-derive = "0.3.0"
